/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 macbook-14.glb -T 
Files: macbook-14.glb [629.72KB] > /Users/enzovillarama/Documents/00 Personal Website/Website-Porfolio/portfolio/public/models/macbook-14-transformed.glb [627.9KB] (0%)
Author: jackbaeten (https://sketchfab.com/jackbaeten)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/macbook-pro-m3-16-inch-2024-8e34fc2b303144f78490007d91ff57c4
Title: macbook pro M3 16 inch 2024
*/

import React, { useState, useEffect } from 'react'
import { useGLTF, useTexture, Text } from '@react-three/drei'
import { useThree } from '@react-three/fiber'

export default function MacbookPro14(props) {
  const { nodes, materials } = useGLTF('/models/macbook-14-transformed.glb')
  const texture = useTexture('/screen.png')
  const [hoveredMesh, setHoveredMesh] = useState(null)
  const [clickedMesh, setClickedMesh] = useState(null)
  const [showAllLabels, setShowAllLabels] = useState(false)

  // Log all mesh info on mount
  useEffect(() => {
    console.log('=== MACBOOK MESH INSPECTION ===')
    Object.keys(nodes).forEach((key) => {
      const node = nodes[key]
      if (node.type === 'Mesh') {
        const bbox = node.geometry.boundingBox
        console.log(`\nMesh: ${key}`)
        console.log('  Position:', { x: node.position.x, y: node.position.y, z: node.position.z })
        console.log('  Rotation:', { x: node.rotation.x, y: node.rotation.y, z: node.rotation.z })
        console.log('  Bounding Box:', bbox ? {
          min: { x: bbox.min.x, y: bbox.min.y, z: bbox.min.z },
          max: { x: bbox.max.x, y: bbox.max.y, z: bbox.max.z }
        } : 'N/A')
      }
    })
  }, [nodes])

  const handleMeshHover = (nodeName) => (e) => {
    e.stopPropagation()
    setHoveredMesh(nodeName)
  }

  const handleMeshClick = (nodeName) => (e) => {
    e.stopPropagation()
    setClickedMesh(clickedMesh === nodeName ? null : nodeName)
    console.log(`\n🎯 CLICKED MESH: ${nodeName}`)
    console.log('Node details:', nodes[nodeName])
  }

  const handleMeshLeave = () => {
    setHoveredMesh(null)
  }

  return (
    <group {...props} dispose={null}>
      {/* Toggle button (press 'L' key to toggle labels) */}
      <group position={[0, 3, 0]}>
        {showAllLabels && (
          <Text
            fontSize={0.3}
            color="white"
            anchorX="center"
            anchorY="middle"
            outlineWidth={0.02}
            outlineColor="black"
          >
            Press 'L' to toggle labels
          </Text>
        )}
      </group>
      {/* Render all meshes with hover/click handlers */}
      <mesh 
        geometry={nodes.Object_10.geometry} 
        material={materials.PaletteMaterial001} 
        rotation={[Math.PI / 2, 0, 0]}
        onPointerEnter={handleMeshHover('Object_10')}
        onPointerLeave={handleMeshLeave}
        onClick={handleMeshClick('Object_10')}
      />
      <mesh 
        geometry={nodes.Object_16.geometry} 
        material={materials.zhGRTuGrQoJflBD} 
        rotation={[Math.PI / 2, 0, 0]}
        onPointerEnter={handleMeshHover('Object_16')}
        onPointerLeave={handleMeshLeave}
        onClick={handleMeshClick('Object_16')}
      />
      <mesh 
        geometry={nodes.Object_20.geometry} 
        material={materials.PaletteMaterial002} 
        rotation={[Math.PI / 2, 0, 0]}
        onPointerEnter={handleMeshHover('Object_20')}
        onPointerLeave={handleMeshLeave}
        onClick={handleMeshClick('Object_20')}
      />
      <mesh 
        geometry={nodes.Object_22.geometry} 
        material={materials.lmWQsEjxpsebDlK} 
        rotation={[Math.PI / 2, 0, 0]}
        onPointerEnter={handleMeshHover('Object_22')}
        onPointerLeave={handleMeshLeave}
        onClick={handleMeshClick('Object_22')}
      />
      <mesh 
        geometry={nodes.Object_30.geometry} 
        material={materials.LtEafgAVRolQqRw} 
        rotation={[Math.PI / 2, 0, 0]}
        onPointerEnter={handleMeshHover('Object_30')}
        onPointerLeave={handleMeshLeave}
        onClick={handleMeshClick('Object_30')}
      />
      <mesh 
        geometry={nodes.Object_32.geometry} 
        material={materials.iyDJFXmHelnMTbD} 
        rotation={[Math.PI / 2, 0, 0]}
        onPointerEnter={handleMeshHover('Object_32')}
        onPointerLeave={handleMeshLeave}
        onClick={handleMeshClick('Object_32')}
      />
      <mesh 
        geometry={nodes.Object_34.geometry} 
        material={materials.eJObPwhgFzvfaoZ} 
        rotation={[Math.PI / 2, 0, 0]}
        onPointerEnter={handleMeshHover('Object_34')}
        onPointerLeave={handleMeshLeave}
        onClick={handleMeshClick('Object_34')}
      />
      <mesh 
        geometry={nodes.Object_38.geometry} 
        material={materials.nDsMUuDKliqGFdU} 
        rotation={[Math.PI / 2, 0, 0]}
        onPointerEnter={handleMeshHover('Object_38')}
        onPointerLeave={handleMeshLeave}
        onClick={handleMeshClick('Object_38')}
      />
      <mesh 
        geometry={nodes.Object_42.geometry} 
        material={materials.CRQixVLpahJzhJc} 
        rotation={[Math.PI / 2, 0, 0]}
        onPointerEnter={handleMeshHover('Object_42')}
        onPointerLeave={handleMeshLeave}
        onClick={handleMeshClick('Object_42')}
      />
      <mesh 
        geometry={nodes.Object_48.geometry} 
        material={materials.YYwBgwvcyZVOOAA} 
        rotation={[Math.PI / 2, 0, 0]}
        onPointerEnter={handleMeshHover('Object_48')}
        onPointerLeave={handleMeshLeave}
        onClick={handleMeshClick('Object_48')}
      />
      <mesh 
        geometry={nodes.Object_54.geometry} 
        material={materials.SLGkCohDDelqXBu} 
        rotation={[Math.PI / 2, 0, 0]}
        onPointerEnter={handleMeshHover('Object_54')}
        onPointerLeave={handleMeshLeave}
        onClick={handleMeshClick('Object_54')}
      />
      <mesh 
        geometry={nodes.Object_58.geometry} 
        material={materials.WnHKXHhScfUbJQi} 
        rotation={[Math.PI / 2, 0, 0]}
        onPointerEnter={handleMeshHover('Object_58')}
        onPointerLeave={handleMeshLeave}
        onClick={handleMeshClick('Object_58')}
      />
      <mesh 
        geometry={nodes.Object_66.geometry} 
        material={materials.fNHiBfcxHUJCahl} 
        rotation={[Math.PI / 2, 0, 0]}
        onPointerEnter={handleMeshHover('Object_66')}
        onPointerLeave={handleMeshLeave}
        onClick={handleMeshClick('Object_66')}
      />
      <mesh 
        geometry={nodes.Object_74.geometry} 
        material={materials.LpqXZqhaGCeSzdu} 
        rotation={[Math.PI / 2, 0, 0]}
        onPointerEnter={handleMeshHover('Object_74')}
        onPointerLeave={handleMeshLeave}
        onClick={handleMeshClick('Object_74')}
      />
      <mesh 
        geometry={nodes.Object_82.geometry} 
        material={materials.gMtYExgrEUqPfln} 
        rotation={[Math.PI / 2, 0, 0]}
        onPointerEnter={handleMeshHover('Object_82')}
        onPointerLeave={handleMeshLeave}
        onClick={handleMeshClick('Object_82')}
      />
      <mesh 
        geometry={nodes.Object_96.geometry} 
        material={materials.PaletteMaterial003} 
        rotation={[Math.PI / 2, 0, 0]}
        onPointerEnter={handleMeshHover('Object_96')}
        onPointerLeave={handleMeshLeave}
        onClick={handleMeshClick('Object_96')}
      />
      <mesh 
        geometry={nodes.Object_107.geometry} 
        material={materials.JvMFZolVCdpPqjj} 
        rotation={[Math.PI / 2, 0, 0]}
        onPointerEnter={handleMeshHover('Object_107')}
        onPointerLeave={handleMeshLeave}
        onClick={handleMeshClick('Object_107')}
      />
      <mesh 
        geometry={nodes.Object_123.geometry} 
        material={materials.sfCQkHOWyrsLmor} 
        rotation={[Math.PI / 2, 0, 0]}
        onPointerEnter={handleMeshHover('Object_123')}
        onPointerLeave={handleMeshLeave}
        onClick={handleMeshClick('Object_123')}
      >
        <meshBasicMaterial map={texture} />
      </mesh>
      <mesh 
        geometry={nodes.Object_127.geometry} 
        material={materials.ZCDwChwkbBfITSW} 
        rotation={[Math.PI / 2, 0, 0]}
        onPointerEnter={handleMeshHover('Object_127')}
        onPointerLeave={handleMeshLeave}
        onClick={handleMeshClick('Object_127')}
      />

      {/* Show labels for hovered/clicked meshes */}
      {Object.keys(nodes).map((key) => {
        const node = nodes[key]
        if (node.type !== 'Mesh') return null
        
        const shouldShow = showAllLabels || hoveredMesh === key || clickedMesh === key
        if (!shouldShow) return null

        const position = node.position || [0, 0, 0]
        return (
          <Text
            key={key}
            position={[position.x, position.y + 0.5, position.z]}
            fontSize={0.15}
            color={clickedMesh === key ? 'yellow' : 'white'}
            anchorX="center"
            anchorY="middle"
            outlineWidth={0.01}
            outlineColor="black"
          >
            {key}
          </Text>
        )
      })}

      {/* Highlight hovered mesh */}
      {hoveredMesh && nodes[hoveredMesh] && (
        <mesh 
          geometry={nodes[hoveredMesh].geometry} 
          position={nodes[hoveredMesh].position}
          rotation={nodes[hoveredMesh].rotation}
        >
          <meshStandardMaterial 
            color="yellow" 
            transparent 
            opacity={0.2}
            wireframe
          />
        </mesh>
      )}
    </group>
  )
}

useGLTF.preload('/models/macbook-14-transformed.glb')
